name: Generate Typedocs
on:
  push:
    branches:
      - main
jobs:
  Install-And-Build:
    runs-on: ubuntu-latest
    steps:
      - run: yarn
      - run: yarn docs
      - run: touch docs/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
          target-folder: typedoc
